name: Deploy Cloud Function

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/setup-gcloud@v0
        with:
          service-account-file: ${{ secrets.GA_SERVICE_ACCOUNT_KEY }}
          project-id: ${{ secrets.GCP_PROJECT_ID }}
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Deploy Cloud Function
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud functions deploy resume_fetch-json \
            --service-account action-cicd-sa-1@nitish-resume-api-cloud.iam.gserviceaccount.com \
            --runtime python3.12.2 \
            --trigger-http \
            --allow-unauthenticated \
            --region asia-south1 \
            --source . \
            --entry-point resume_fetch

